### ISSUE TITLE
chore(deps): bump otel

### ISSUE THREAD

**Issue by gupadhyaya** [celestiaorg/go-fraud#19]
go-header has bumped otel and it will create conflicts when rollkit uses both go-header and go-fraud for otel package. we need to bump otel here to resolve the build failure as done in https://github.com/celestiaorg/go-header/pull/84, especially when rollkit uses go-header v0.2.12: https://github.com/celestiaorg/go-header/releases/tag/v0.2.12

**Comment by Wondertan** [comment]
@gupadhyaya, we bumped Otel here via https://github.com/celestiaorg/go-fraud/pull/17
